services:
  mysql:
    image: mysql:8
    container_name: movie-mysql
    environment:
      MYSQL_DATABASE: moviebookingdatabase
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    image: movie-backend
    container_name: movie-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moviebookingdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_KEY: 3fKL7PlxDY5zPwH1uE8YjS1Yx3LPqQKzv8OV9eT5nFc=
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
