name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build Backend
      - name: Build MovieBookingApplication (Backend)
        run: |
          cd MovieBookingApplication
          mvn clean package -DskipTests

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend Docker image
      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-backend:latest ./MovieBookingApplication

      # Push Backend image
      - name: Push Backend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/movie-backend:latest

      # Build Frontend Docker image
      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-frontend:latest ./MovieBookingApplicationFrontend/Movie-Booking-Frontend

      # Push Frontend image
      - name: Push Frontend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/movie-frontend:latest
